#!/usr/bin/env node

var fs =			require('fs');
var path =			require('path');

var stations =		require('vbb-static/stations');
var util =			require('vbb-util');





var index = [], id;
for (id in stations) {
	index.push({
		id:		parseInt(id),
		name:	stations[id].name,
		keys:	util.locations.stations.tokenize(stations[id].name),
		weight:	stations[id].weight
	});
}

var target = path.join(__dirname, '../data/index.json');
fs.writeFileSync(target, JSON.stringify(index));
